<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-38D869DN" failures="1" tests="5" name="Command line test" time="45.221" errors="0" timestamp="2023-02-07T10:31:41 GMT-05:00">
  <testcase classname="tests.LoginCredsTest" name="invaidPassword" time="1.651"/>
  <testcase classname="tests.LoginCredsTest" name="invalidEmail" time="1.641">
    <skipped/>
  </testcase> <!-- invalidEmail -->
  <testcase classname="tests.LoginCredsTest" name="invalidEmail" time="1.525">
    <failure type="java.lang.AssertionError" message="expected [Usr does not exist.] but found [User does not exist.]">
      <![CDATA[java.lang.AssertionError: expected [Usr does not exist.] but found [User does not exist.]
at tests.LoginCredsTest.invalidEmail(LoginCredsTest.java:30)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 39 stack frames]]>
    </failure>
  </testcase> <!-- invalidEmail -->
  <testcase classname="tests.SubmitOrderTest" name="regression" time="6.552"/>
  <testcase classname="tests.SubmitOrderTest" name="regression" time="7.543"/>
</testsuite> <!-- Command line test -->
