<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="LAPTOP-38D869DN" failures="1" tests="3" name="Grouping" time="56.244" errors="0" timestamp="2023-02-07T10:49:28 GMT-05:00">
  <testcase classname="tests.LoginCredsTest" name="invaidPassword" time="1.606"/>
  <testcase classname="tests.LoginCredsTest" name="invalidEmail" time="1.306">
    <skipped/>
  </testcase> <!-- invalidEmail -->
  <testcase classname="tests.LoginCredsTest" name="invalidEmail" time="2.102">
    <failure type="java.lang.AssertionError" message="expected [Usr does not exist.] but found [User does not exist.]">
      <![CDATA[java.lang.AssertionError: expected [Usr does not exist.] but found [User does not exist.]
at tests.LoginCredsTest.invalidEmail(LoginCredsTest.java:30)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 35 stack frames]]>
    </failure>
  </testcase> <!-- invalidEmail -->
  <testcase classname="tests.SubmitOrderTest" name="regression" time="0.0">
    <ignored/>
  </testcase> <!-- regression -->
</testsuite> <!-- Grouping -->
